# SPDX-License-Identifier: MIT
---
# Put internal variables here with Red Hat specific values.

__spark_service_path: /usr/lib/systemd/system
__spark_packages_extra:
  - pcp-pmda-spark
__spark_packages_export:
  - pcp-export-pcp2spark
